name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/checkout@v2
        if: ${{ github.event_name != 'pull_request' }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Move CheckStyle badge
        if: always()
        run: mv ./backend/target/site/badges/checkstyle-result.svg ./.github/badges/

      - name: Delete old JavaDoc
        run: rm -rf docs

      - name: Generate JavaDoc
        working-directory: ./backend
        run: mvn javadoc:javadoc

